### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by iterion** [CharlieHess/slack-poker-bot#16]
To further support deployability it might be nice to have a Dockerfile and perhaps an automated build through the docker registry.

**Comment by danielstjules** [comment]
In the meantime, could just add your own Dockerfile and docker-compose.yml

**Comment by kordless** [comment]
I build a deployment for Giant Swarm, which includes a Dockerfile that can be used locally: https://github.com/kordless/swarm-holdem. Usage is:

```
make run
```

Alternately, awinder on HN posted up a Docker hub image: https://hub.docker.com/r/awinder/slack-poker-bot/, who's source is located here: https://github.com/CharlieHess/slack-poker-bot

**Comment by drudge** [comment]
I created something quick for testing:

```
from ubuntu:14.04

env SLACK_POKER_BOT_TOKEN xxx

run apt-get update && apt-get install -y curl
run curl -sL https://deb.nodesource.com/setup_0.12 | bash -
run apt-get install -y nodejs python build-essential

add https://github.com/CharlieHess/slack-poker-bot/archive/master.tar.gz /tmp/master.tar.gz

run mkdir -p /app && tar zxf /tmp/master.tar.gz --strip-components=1 -C /app
workdir /app
run npm install

cmd [ "node", "src/main.js” ]
```

**Comment by CharlieHess** [comment]
There are lots of options to choose from. Here's [another](https://hub.docker.com/r/jdcioccio/slack-poker-bot/).
