### ISSUE TITLE
Shuffle algorithm is incorrect

### ISSUE THREAD

**Issue by flakmonkey** [CharlieHess/slack-poker-bot#21]
Sorry I didn't just create a pull request, but I'm on my mobile.

I believe the shuffle algorithm here is incorrect: https://github.com/CharlieHess/slack-poker-bot/blob/master/src/deck.js

My understanding is that you only want to swap the current card with cards that have a greater index in the deck, basically creating a shuffled and unshuffled part of the deck. It's explained better here: http://www.i-programmer.info/programming/theory/2744-how-not-to-shuffle-the-kunth-fisher-yates-algorithm.html

**Comment by CharlieHess** [comment]
Thanks for reporting @flakmonkey. Fixed [here](https://github.com/CharlieHess/slack-poker-bot/commit/332f393ac7527800036ca24bf5b76d84af531a41).
