### ISSUE TITLE
All-in => fold, winning player loses everything

### ISSUE THREAD

**Issue by aristretto** [CharlieHess/slack-poker-bot#23]
![screenshot 2015-09-01 15 47 14](https://cloud.githubusercontent.com/assets/1207032/9619075/e09ae5a6-50c0-11e5-9d56-0d2b5bd977e4.png)

Shouldn't I end up with `> $0` for the next round?

**Comment by CharlieHess** [comment]
Mos Def. I'll try to recreate this in a [spec](https://github.com/CharlieHess/slack-poker-bot/blob/master/tests/texas-holdem-spec.js#L53). Thanks for the feedback!

**Comment by domness** [comment]
<img width="388" alt="screen shot 2015-09-02 at 09 47 32" src="https://cloud.githubusercontent.com/assets/95579/9626751/a928a13e-5157-11e5-978b-d9253dba1b73.png">

**Comment by aendrew** [comment]
Just had the same happen to me! Kinda deflating! :smile:

**Comment by CharlieHess** [comment]
Fix is incoming, I feel your pain:
![](https://s3.amazonaws.com/f.cl.ly/items/1E0N060U1C0n3F0J2z1O/Image%202015-09-02%20at%206.51.56%20PM.png)

**Comment by aendrew** [comment]
Brilliant, many thanks! :+1: :shipit:
