### ISSUE TITLE
Configurable timeouts

### ISSUE THREAD

**Issue by ridhoq** [CharlieHess/slack-poker-bot#24]
Would you be interested in a pull request that makes the polling timeouts configurable via some file? My usecase being: I'd like to play this with buddies at work asynchronously.

**Comment by CharlieHess** [comment]
Most definitely. Had a few requests for this from work friends already.

**Comment by CharlieHess** [comment]
See #8, had plans to work this into a config file.

**Comment by Droogans** [comment]
Please consider [this response](https://github.com/CharlieHess/slack-poker-bot/issues/8#issuecomment-136854847) stating that you should be able to drive this config at game start in slack.

```
@pokerbot deal timeout=15m
```

Something like that.

**Comment by CharlieHess** [comment]
Yeah I'm onboard with that. `timeout=0` for no timeouts at all.

**Comment by CharlieHess** [comment]
Wrapping this up into #8.
