### ISSUE TITLE
Use :hearts:, etc. emoticons for your DM'd hand.

### ISSUE THREAD

**Issue by kordless** [CharlieHess/slack-poker-bot#27]
Slack supports the use of :hearts:, :spades:, :diamonds: and :clubs: emoticons. Looking at the code, it looks like a simple parse and lookup of the card (eg. 3h) would net an output that looked a bit more familiar:

3 of :hearts:

If I have a bit of time, I may attempt a PR. Disclaimer: I'm a Python guy. :)

**Comment by CharlieHess** [comment]
This was already implemented [here](https://github.com/CharlieHess/slack-poker-bot/pull/13). Slack converts the Unicode to a nice emoji.
