### ISSUE TITLE
Running out of cards

### ISSUE THREAD

**Issue by alansutherland** [CharlieHess/slack-poker-bot#34]
Only a few hands in to a game we seemed to run out of cards:

![pokerbug](https://cloud.githubusercontent.com/assets/4670058/9686717/2f466e10-531d-11e5-8d76-f4e62a7f1f9b.png)

**Comment by stephenyeargin** [comment]
#29 _should_ fix this issue if you've pulled down lately.

**Comment by CharlieHess** [comment]
Yep, should be fixed already. @alansutherland can you confirm?

**Comment by CharlieHess** [comment]
Closing this out unless we get a repro on master.

**Comment by alansutherland** [comment]
Will test again and get back to you
