### ISSUE TITLE
Card images

### ISSUE THREAD

**Issue by sallesma** [CharlieHess/slack-poker-bot#42]
The image of the cards does not match the cards symbols sent by the bot:
![capture d ecran 2015-09-07 a 14 33 33](https://cloud.githubusercontent.com/assets/3810795/9717008/4d5a7654-556f-11e5-95a1-75e5bff4620e.png)

**Comment by MasterNayru** [comment]
I've noticed that if the Queen of Clubs is on the board that it will cause either the wrong cards to be displayed or a completely wrong set of the cards to be shown like in the image above.

**Comment by CharlieHess** [comment]
This happens when uploading a board image times out.

**Comment by CharlieHess** [comment]
Fixed [here](https://github.com/CharlieHess/slack-poker-bot/commit/843aa77efd9d3e9a7f1f9e1ef70bdab9f9b99bd0).
