### ISSUE TITLE
Switching between DM and Channel stalls play

### ISSUE THREAD

**Issue by tvb** [CharlieHess/slack-poker-bot#43]
I think switching between the DM of your cards and back to the channel to play really stalls the game.

**Comment by chezpaul** [comment]
+2

**Comment by CharlieHess** [comment]
You should be getting a pop-up notification for each DM. If not, try tweaking your notification settings?

**Comment by richardtape** [comment]
The pop-up notification is definitely better than having to switch between a DM and the channel. However, I was thinking of a slightly different UX. The slackbot can 'whisper' (prob. not the right terminology) something to you - and only you - in the channel you're in. Is this available via the API? If so, that could be pretty awesome.

**Comment by CharlieHess** [comment]
Not available in the API yet. :disappointed:
Good suggestion though.

**Comment by corneadoug** [comment]
That could also have been a good idea in case you play a game in multiple channels

**Comment by CharlieHess** [comment]
Closing until there's another option for communicating hole cards.
