### ISSUE TITLE
Custom configuration, specified in a message to PokerBot

### ISSUE THREAD

**Issue by CharlieHess** [CharlieHess/slack-poker-bot#8]
It would be nice to read in some configuration file and automatically set things like:
* Blind levels
* Starting chip stacks
* Timeout for player actions
* Pause duration between hands

**Comment by geobmx540** [comment]
Would even be better if optionally you could start games with these configurations - rather than requiring a config file - maybe the config file sets the default game

**Comment by CaptainPalapa** [comment]
Oh, this is a very nice idea.  The biggest issue I've found, though, is having to switch channels to see your cards.  I know (from my own bot building experience) that you simply can't do a private message in-channel without a /slash command.  So not sure there.    SlackDeck (like TweetDeck) would help!

**Comment by CharlieHess** [comment]
The foundations for this are in place, and player timeout is now configurable.
